### ISSUE TITLE
which Ticket Scanner app

### ISSUE THREAD

**Issue by derralf** [TheBnl/event-tickets-app#1]
Hi,
which "Ticket Scanner app" do you mean? Can you provide links?
thanks

**Comment by TheBnl** [comment]
Hi, yes i should update the readme with those!
Apple: https://itunes.apple.com/nl/app/xd-ticket-scanner/id1250791189?mt=8
Android: https://play.google.com/store/apps/details?id=nl.xd.ticketscanner2

**Comment by derralf** [comment]
thanks
